version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./django/dockerfile
    command: ./entrypoint.sh
    volumes:
      - ./django:/code
    depends_on:
      - db
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "PYTHONUNBUFFERED=1"
    expose:
      - 5432

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4242:80"
    volumes:
      - ./website:/usr/share/nginx/html/website
    depends_on:
      - django
      - ai

  ai:
    build:
      context: .
      dockerfile: ai/Dockerfile
    volumes:
      - ./ai:/app
    depends_on:
      - db
    environment:
      - SOME_ENV_VAR=example
    ports:
      - "5678:5678"

volumes:
  postgres_data:
