version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./django/dockerfile
    command: ./entrypoint.sh
    volumes:
      - ./django:/code
    depends_on:
      - db
    environment:
      - "DJANGO_SETTINGS_MODULE=backend.settings"
      - "PYTHONUNBUFFERED=1"
    expose:
      - 5432

  nginx:
      build:
        context: ./frontend  # This should be the directory that contains the custom Dockerfile for Nginx
        dockerfile: dockerfile  # The name of your Dockerfile
      ports:
        - "4242:80"  # Map port 4242 on the host to port 80 in the container
      volumes:
        - ./website:/usr/share/nginx/html/website  # Make sure this points to where your static files are
      depends_on:
        - django


volumes:
  postgres_data:
