# Generated by Django 3.2.25 on 2024-05-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/pictures/default.jpg', null=True, upload_to='media/pictures/'),
        ),
    ]
