# Generated by Django 3.2.25 on 2024-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pictures/default.jpg', null=True, upload_to='pictures/'),
        ),
    ]
