# Generated by Django 3.2.24 on 2024-02-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20240217_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
