# Generated by Django 3.2.25 on 2024-04-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
