# Generated by Django 3.2.25 on 2024-04-03 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
