# Generated by Django 3.2.25 on 2024-04-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='backend.player'),
        ),
    ]
