# Generated by Django 3.2.25 on 2024-04-18 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_game_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_backend_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
