# Generated by Django 3.2.25 on 2024-04-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_in_game',
            field=models.BooleanField(default=False),
        ),
    ]
