# Generated by Django 3.2.25 on 2024-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_customuser_is_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_in_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
