# Generated by Django 3.2.25 on 2024-05-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_gamesettings_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='player1',
            field=models.CharField(default='p1', max_length=12),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='player2',
            field=models.CharField(default='p2', max_length=12),
        ),
    ]
