# Use the official Python image from the Docker Hub
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

COPY django /code/

# Install dependencies
COPY django/requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

#CMD entrypoint.sh
